## 선거인 명부 확정 상황
  - 중앙선거관리위원회 선거통계시스템에서 다운로드 가능
  > http://info.nec.go.kr/main/showDocument.xhtml?electionId=0020200415&topMenuId=BI&secondMenuId=BIPB02

In [215]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [216]:
base_path = '../data/voter'
SIDO = os.listdir(base_path)
print(SIDO)

['[제21대_국회의원선거]_선거인명부_확정상황_전라북도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_경상북도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_충청북도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_부산광역시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_서울특별시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_인천광역시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_전라남도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_대전광역시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_세종특별자치시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_경상남도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_제주특별자치도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_충청남도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_광주광역시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_강원도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_대구광역시.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_경기도.xlsx', '[제21대_국회의원선거]_선거인명부_확정상황_울산광역시.xlsx']

In [217]:
# 파일 오픈
df = pd.read_excel(os.path.join(base_path, '[제21대_국회의원선거]_선거인명부_확정상황_서울특별시.xlsx'))
df.head()

,중앙선거관리위원회 선거통계시스템,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,[제21대 국회의원선거] 선거인명부 확정상황,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[국회의원선거][서울특별시],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,선거구명,구시군명,읍면\n동수,투표\n구수,인구수\n(선거인명부작성\n기준일현재),확정된 선거인수,NaN,NaN,거소투표\n신고인명부\n등재자수,선상투표\n신고인명부\n등재자수,인구수에 대한\n선거인수\n비율(%),세대수,NaN
3,합계,,424,"2,252","9,736,986\n(29,483 , 0)",계,NaN,"8,465,419\n(25,796 , 0)","12,947\n(7)",222\n(0),86.9,"4,397,162\n(25,796 , 0)",NaN
4,NaN,NaN,NaN,NaN,NaN,남,NaN,"4,088,006\n(10,513 , 0)","10,093\n(5)",216\n(0),NaN,NaN,NaN

In [218]:
# 파일 재 오픈
df = pd.read_excel(os.path.join(base_path, '[제21대_국회의원선거]_선거인명부_확정상황_서울특별시.xlsx'), skiprows=2)
df.head()

,[국회의원선거][서울특별시],Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,선거구명,구시군명,읍면\n동수,투표\n구수,인구수\n(선거인명부작성\n기준일현재),확정된 선거인수,NaN,NaN,거소투표\n신고인명부\n등재자수,선상투표\n신고인명부\n등재자수,인구수에 대한\n선거인수\n비율(%),세대수,NaN
1,합계,,424,"2,252","9,736,986\n(29,483 , 0)",계,NaN,"8,465,419\n(25,796 , 0)","12,947\n(7)",222\n(0),86.9,"4,397,162\n(25,796 , 0)",NaN
2,NaN,NaN,NaN,NaN,NaN,남,NaN,"4,088,006\n(10,513 , 0)","10,093\n(5)",216\n(0),NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,여,NaN,"4,377,413\n(15,283 , 0)","2,854\n(2)",6\n(0),NaN,NaN,NaN
4,종로구,소계,17,43,"151,296\n(891 , 0)",계,NaN,"134,516\n(778 , 0)",247\n(0),4\n(0),88.9,"75,228\n(778 , 0)",NaN

In [219]:
# 시도명 추출
sido = df.columns[0].split('[')[-1].replace(']','')

# 컬럼 재설정
df = df.rename(columns=df.iloc[0])

In [220]:
# 선거구데이터만 추출

df = df[df['선거구명'].notnull()]
df = df[df['구시군명'] == '소계']
df.head()

,선거구명,구시군명,읍면\n동수,투표\n구수,인구수\n(선거인명부작성\n기준일현재),확정된 선거인수,NaN,NaN,거소투표\n신고인명부\n등재자수,선상투표\n신고인명부\n등재자수,인구수에 대한\n선거인수\n비율(%),세대수,NaN
4,종로구,소계,17,43,"151,296\n(891 , 0)",계,NaN,"134,516\n(778 , 0)",247\n(0),4\n(0),88.9,"75,228\n(778 , 0)",NaN
10,중구성동구갑,소계,13,52,"217,842\n(656 , 0)",계,NaN,"192,161\n(571 , 0)",244\n(0),3\n(0),88.2,"102,207\n(571 , 0)",NaN
16,중구성동구을,소계,19,63,"207,715\n(1,029 , 0)",계,NaN,"183,779\n(921 , 0)",348\n(1),1\n(0),88.5,"98,694\n(921 , 0)",NaN
22,용산구,소계,16,59,"229,623\n(1,677 , 0)",계,NaN,"203,233\n(1,516 , 0)",252\n(0),7\n(0),88.5,"112,463\n(1,516 , 0)",NaN
28,광진구갑,소계,8,42,"179,793\n(398 , 0)",계,NaN,"156,559\n(366 , 0)",204\n(0),2\n(0),87.1,"81,984\n(366 , 0)",NaN

In [221]:
# 선거구 명 및 선거구 수 확인
df['선거구명'].unique(), len(df['선거구명'])

(array(['종로구', '중구성동구갑', '중구성동구을', '용산구', '광진구갑', '광진구을', '동대문구갑', '동대문구을',
        '중랑구갑', '중랑구을', '성북구갑', '성북구을', '강북구갑', '강북구을', '도봉구갑', '도봉구을',
        '노원구갑', '노원구을', '노원구병', '은평구갑', '은평구을', '서대문구갑', '서대문구을', '마포구갑',
        '마포구을', '양천구갑', '양천구을', '강서구갑', '강서구을', '강서구병', '구로구갑', '구로구을',
        '금천구', '영등포구갑', '영등포구을', '동작구갑', '동작구을', '관악구갑', '관악구을', '서초구갑',
        '서초구을', '강남구갑', '강남구을', '강남구병', '송파구갑', '송파구을', '송파구병', '강동구갑',
        '강동구을'], dtype=object),
 49)

In [222]:
# 필요 컬럼만 추출
district = df[['선거구명', '인구수\n(선거인명부작성\n기준일현재)']]

# 컬럼명 변경
district.columns = ['선거구명', '유권자 수']

# 유권자 수 컬럼 처리
# 유권자 수 컬럼에 존재하는 ,(콤마)를 제거 후 \n(줄바꿈 기호)를 기준으로 분할하여 첫번째 분할된 레코드만 가지고 옴
district['유권자 수'] = district['유권자 수'].str.replace(',', '').str.split('\n').str[0].astype('int64')

district.head()

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

      선거구명   유권자 수
4      종로구  151296
10  중구성동구갑  217842
16  중구성동구을  207715
22     용산구  229623
28    광진구갑  179793

In [223]:
# 모든 광역시도를 하나의 데이터 프레임으로 결합

election_district = pd.DataFrame()

for file in SIDO:
    df = pd.read_excel(os.path.join(base_path, file), skiprows=2)

    # 시도명 추출
    sido = df.columns[0].split('[')[-1].replace(']','')

    # 컬럼 재설정
    df = df.rename(columns=df.iloc[0])

    df = df[df['선거구명'].notnull()]
    df = df[df['구시군명'] == '소계']

    district = df[['선거구명', '인구수\n(선거인명부작성\n기준일현재)']]
    district.columns = ['선거구명', '유권자 수']
    district['유권자 수'] = district['유권자 수'].str.replace(',', '').str.split('\n').str[0].astype('int64')
    district['광역시도명'] = sido

    if sido[-2:] in ['남도', '북도']:
        district['시도명'] = sido[0] + sido[2]
    else:
        district['시도명'] = sido[:2]


    election_district = pd.concat([election_district, district])
    election_district.reset_index(drop=True, inplace=True)
    
election_district.head()

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   선거구명   유권자 수 광역시도명 시도명
0  전주시갑  171863  전라북도  전북
1  전주시을  199526  전라북도  전북
2  전주시병  284058  전라북도  전북
3   군산시  268750  전라북도  전북
4  익산시갑  136377  전라북도  전북

In [224]:
election_district.sort_values('선거구명')

             선거구명   유권자 수  광역시도명 시도명
90           강남구갑  192324  서울특별시  서울
92           강남구병  186403  서울특별시  서울
91           강남구을  166628  서울특별시  서울
96           강동구갑  265882  서울특별시  서울
97           강동구을  185982  서울특별시  서울
..            ...     ...    ...  ..
159        홍성군예산군  179079   충청남도  충남
175  홍천군횡성군영월군평창군  195846    강원도  강원
239          화성시갑  239206    경기도  경기
241          화성시병  279140    경기도  경기
240          화성시을  306909    경기도  경기

[253 rows x 4 columns]

In [225]:
# 광역시도별 선거구 수 확인

election_district.groupby('광역시도명')['선거구명'].agg(['count']).sort_values('count', ascending=False)

         count
광역시도명
경기도         59
서울특별시       49
부산광역시       18
경상남도        16
인천광역시       13
경상북도        13
대구광역시       12
충청남도        11
전라북도        10
전라남도        10
강원도          8
광주광역시        8
충청북도         8
대전광역시        7
울산광역시        6
제주특별자치도      3
세종특별자치시      2

In [226]:
# 선거구 수 확인
election_district.groupby('광역시도명')['선거구명'].agg(['count']).sum()

count    253
dtype: int64

In [227]:
# 광역시도별 유권자수 수 확인
election_district.groupby('광역시도명')['유권자 수'].agg(['sum']).sort_values('sum', ascending=False)

              sum
광역시도명
경기도      13276036
서울특별시     9736986
부산광역시     3410199
경상남도      3356914
인천광역시     2954295
경상북도      2655190
대구광역시     2432827
충청남도      2120663
전라남도      1860430
전라북도      1813724
충청북도      1598418
강원도       1539225
대전광역시     1472287
광주광역시     1455861
울산광역시     1144639
제주특별자치도    670828
세종특별자치시    344746

In [228]:
# 유권자 수 대비 선거구 수 확인
district = election_district.groupby('광역시도명')['선거구명'].agg(['count'])
voter = election_district.groupby('광역시도명')['유권자 수'].agg(['sum'])

rate = voter['sum'] / district['count']
rate.sort_values(ascending=False)

광역시도명
인천광역시      227253.461538
경기도        225017.559322
제주특별자치도    223609.333333
대전광역시      210326.714286
경상남도       209807.125000
경상북도       204245.384615
대구광역시      202735.583333
충청북도       199802.250000
서울특별시      198714.000000
충청남도       192787.545455
강원도        192403.125000
울산광역시      190773.166667
부산광역시      189455.500000
전라남도       186043.000000
광주광역시      181982.625000
전라북도       181372.400000
세종특별자치시    172373.000000
dtype: float64

In [230]:
election_district.to_excel('../data/korea_voter_21th_election.xlsx', index=False)