## 카토그램
  - 실제 면적을 기반으로 작성되는 일반적인 지도와는 달리, 특정 통계 정보를 기반으로 작성된 지도를 의미함.
  
  > Ref] https://namu.wiki/w/%EC%B9%B4%ED%86%A0%EA%B7%B8%EB%9E%A8

In [1]:
import pandas as pd

In [2]:
# 미리 준비되어있는 지도를 이용함

election_map = pd.read_excel('../data/korea_map_21th_election_type_b.xlsx')
election_map

,Y,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,NaN,NaN,NaN,NaN,경기 파주시갑,경기 파주시을,NaN,강원 춘천시철원군화천군양구군갑,강원 춘천시철원군화천군양구군을,강원 속초시인제군고성군양양군,강원 강릉시,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,경기 김포시갑,경기 김포시을,경기 동두천시연천군,경기 의정부시갑,경기 의정부시을,경기 남양주시갑,경기 남양주시을,강원 원주시갑,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,인천 중구강화군옹진군,경기 고양시갑,경기 고양시을,경기 고양시병,경기 고양시정,서울 강북구갑,서울 도봉구갑,서울 노원구갑,경기 남양주시병,강원 원주시을,NaN,NaN,NaN,NaN
3,3,NaN,NaN,인천 서구갑,인천 서구을,인천 계양구갑,인천 계양구을,인천 동구미추홀구갑,인천 동구미추홀구을,서울 은평구갑,서울 강북구을,서울 도봉구을,서울 노원구을,경기 포천시가평군,강원 홍천군횡성군영월군평창군,NaN,NaN,NaN
4,4,NaN,NaN,인천 연수구갑,인천 연수구을,인천 부평구갑,인천 부평구을,서울 서대문구갑,서울 서대문구을,서울 은평구을,서울 성북구갑,서울 성북구을,서울 노원구병,경기 양주시,강원 동해시태백시삼척시정선군,NaN,NaN,NaN
5,5,NaN,NaN,NaN,NaN,인천 남동구갑,인천 남동구을,서울 마포구갑,서울 마포구을,서울 종로구,서울 동대문구갑,서울 동대문구을,서울 중랑구갑,서울 중랑구을,경기 구리시,경기 여주시양평군,NaN,NaN
6,6,NaN,NaN,경기 안산시상록구갑,경기 시흥시갑,서울 강서구갑,서울 양천구갑,서울 양천구을,서울 동작구갑,서울 동작구을,서울 용산구,서울 중구성동구갑,서울 중구성동구을,서울 광진구갑,서울 광진구을,경기 이천시,NaN,NaN
7,7,NaN,경기 안산시상록구을,경기 안산시단원구갑,경기 시흥시을,서울 강서구을,서울 강서구병,서울 영등포구갑,서울 영등포구을,서울 서초구갑,서울 서초구을,서울 송파구갑,서울 송파구을,서울 강동구갑,경기 광주시갑,경기 광주시을,NaN,NaN
8,8,NaN,NaN,경기 안산시단원구을,경기 부천시갑,경기 부천시을,경기 부천시병,서울 관악구갑,서울 관악구을,서울 강남구갑,서울 강남구을,서울 강남구병,서울 송파구병,서울 강동구을,경기 용인시갑,경기 용인시을,경기 용인시정,NaN
9,9,NaN,NaN,NaN,경기 부천시정,경기 평택시갑,경기 평택시을,서울 금천구,서울 구로구갑,서울 구로구을,경기 수원시갑,경기 수원시을,경기 성남시분당구갑,경기 성남시분당구을,경기 하남시,경기 용인시병,NaN,NaN
10,10,NaN,NaN,NaN,NaN,경기 화성시갑,경기 광명시갑,경기 광명시을,경기 군포시,경기 의왕시과천시,경기 수원시병,경기 수원시정,경기 수원시무,경기 성남시수정구,경기 성남시중원구,경북 상주시문경시,경북 군위군의성군청송군영덕군,경북 영주시영양군봉화군울진군
11,11,NaN,NaN,NaN,NaN,경기 화성시을,경기 화성시병,경기 안양시만안구,경기 안양시동안구갑,경기 안양시동안구을,경기 오산시,경기 안성시,대구 중구남구,대구 동구갑,대구 동구을,경북 고령군성주군칠곡군,경북 경주시,NaN
12,12,NaN,충남 당진시,충남 천안시갑,충남 천안시을,세종 세종특별자치시갑,세종 세종특별자치시을,충북 청주시상당구,충북 청주시서원구,충북 청주시흥덕구,충북 제천시단양군,대구 서구,대구 북구갑,대구 북구을,경북 구미시갑,경북 구미시을,NaN,NaN
13,13,NaN,충남 서산시태안군,충남 논산시계룡시금산군,충남 천안시병,충남 보령시서천군,충북 보은군옥천군영동군괴산군,충북 증평군진천군음성군,충북 청주시청원구,충북 충주시,대구 수성구갑,대구 수성구을,대구 달성군,경북 안동시예천군,경북 포항시남구울릉군,경북 포항시북구,NaN,NaN
14,14,NaN,NaN,충남 아산시갑,충남 아산시을,대전 서구갑,대전 서구을,대전 중구,대전 동구,대구 달서구갑,대구 달서구을,대구 달서구병,경북 김천시,경북 영천시청도군,경북 경산시,NaN,NaN,NaN
15,15,NaN,NaN,전북 김제시부안군,충남 홍성군예산군,충남 공주시부여군청양군,대전 유성구갑,대전 유성구을,대전 대덕구,경남 김해시갑,경남 김해시을,경남 산청군함양군거창군합천군,울산 동구,울산 북구,울산 울주군,NaN,NaN,NaN
16,16,전북 군산시,전북 전주시갑,전북 전주시을,전북 전주시병,전북 정읍시고창군,전북 남원시임실군순창군,경남 밀양시의령군함안군창녕군,경남 통영시고성군,경남 창원시의창구,경남 창원시성산구,경남 창원시마산합포구,울산 중구,울산 남구갑,울산 남구을,NaN,NaN,NaN
17,17,NaN,전북 익산시갑,전북 익산시을,광주 서구갑,광주 서구을,광주 북구갑,광주 북구을,경남 진주시갑,경남 진주시을,경남 창원시마산회원구,경남 창원시진해구,부산 사하구갑,부산 사하구을,부산 동래구,NaN,NaN,NaN
18,18,NaN,전북 완주군진안군무주군장수군,광주 광산구갑,광주 광산구을,광주 동구남구갑,광주 동구남구을,경남 거제시,경남 양산시갑,부산 북구강서구갑,부산 북구강서구을,부산 부산진구갑,부산 부산진구을,부산 서구동구,NaN,NaN,NaN,NaN
19,19,NaN,전남 목포시,전남 나주시화순군,전남 담양군함평군영광군장성군,전남 고흥군보성군장흥군강진군,경남 사천시남해군하동군,경남 양산시을,부산 금정구,부산 연제구,부산 수영구,부산 사상구,부산 기장군,NaN,NaN,NaN,NaN,NaN
20,20,NaN,NaN,전남 해남군완도군진도군,전남 여수시갑,전남 여수시을,NaN,부산 남구갑,부산 남구을,부산 해운대구갑,부산 해운대구을,부산 중구영도구,NaN,NaN,NaN,NaN,NaN,NaN
21,21,NaN,전남 영암군무안군신안군,전남 순천시광양시곡성군구례군갑,전남 순천시광양시곡성군구례군을,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,NaN,NaN,NaN,NaN,NaN,NaN,제주 제주시갑,제주 제주시을,제주 서귀포시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
election_map = election_map.set_index('Y')

election_map = election_map.fillna(0)

col = election_map.columns
idx = election_map.index

In [4]:
# 카토그램에서 X, Y좌표 및 선거구 명 추출

X = []
Y = []
SIDO = []
SIGUNGU = []

for c in col:
    for i in idx:
        if election_map.loc[i, c]:
            X.append(c)
            Y.append(i)

            loc = election_map.loc[i, c].replace('\n', ' ').replace('  ', ' ').split()
            SIDO.append(loc[0])
            SIGUNGU.append(loc[1])

In [5]:
df = pd.DataFrame({
    'X' : X,
    'Y' : Y,
    '시도명': SIDO,
    '선거구명': SIGUNGU,
})

df.to_excel('../data/korea_map_21th_election_type_b_data.xlsx', index=False)

In [8]:
df[df['시도명'] == '광주']

    X   Y 시도명   선거구명
20  2  18  광주   광산구갑
36  3  17  광주    서구갑
37  3  18  광주   광산구을
58  4  17  광주    서구을
59  4  18  광주  동구남구갑
79  5  17  광주    북구갑
80  5  18  광주  동구남구을
98  6  17  광주    북구을